# Generated by Django 4.0.5 on 2022-06-18 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_destination_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.brand')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.destination')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.season')),
            ],
        ),
    ]
