# Generated by Django 4.0.5 on 2022-06-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_shoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_size', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='shoe',
            name='ruSizes',
            field=models.ManyToManyField(to='shoes.size'),
        ),
    ]
