# Generated by Django 4.0.5 on 2022-06-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0008_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
    ]
