# Generated by Django 4.0.5 on 2022-06-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0012_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
