# Generated by Django 4.0.5 on 2022-06-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0014_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
